### ISSUE TITLE
Still getting "Argument 4 is not an integer" error after trying multiple things like parsing it as an integer and rounding

### ISSUE THREAD

**Issue by Xicad** [ReportCardsMC/SKNoise#9]
https://pastebin.com/PUcz39Az
using this, it still gives the error "%the 4th argument%" parsed as an integer is not an integer

latest.log: https://pastebin.com/SssWjqdV

**Comment by ReportCardsMC** [comment]
I'll look into it, but maybe just try just arg-4? Since it's already an integer

**Comment by ReportCardsMC** [comment]
I'm looking into a fix for this now, not sure why it's happening completely

**Comment by ReportCardsMC** [comment]
After doing some work and even changing the type required for Octaves completely, this may be an error with how skript parses things, but don't quote me on that. I am still actively looking into this

**Comment by ReportCardsMC** [comment]
Fixed in latest version
